spring.datasource.url=jdbc:postgresql://localhost:5432/payment_gateway

spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration

# Secret key used to sign tokens — change this in production, never commit real secrets to GitHub
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Token expiry in milliseconds — 86400000 = 24 hours
jwt.expiration=86400000

#SPRING KAFKA CONFIGURATION

# Address of the running Kafka broker
spring.kafka.bootstrap-servers=localhost:9092

# Producer configurations (Sending Events)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer configurations (Receiving Events)
spring.kafka.consumer.group-id=payment-processing-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# Tell Spring Kafka to trust deserialization of our event model packages
spring.kafka.consumer.properties.spring.json.trusted.packages=com.payment.dto,com.payment.event

#  REDIS CONFIGURATION
spring.data.redis.host=localhost
spring.data.redis.port=6379
