spring.datasource.url=jdbc:postgresql://localhost:5432/payment_gateway

spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
# Secret key used to sign tokens — change this in production, never commit real secrets to GitHub
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Token expiry in milliseconds — 86400000 = 24 hours
jwt.expiration=86400000